POST http://localhost:9002/date/add
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###
POST http://localhost:9002/date/add
Content-Type: application/json

{
  "id": 1,
  "name":"yangfei",
  "createTime": "2022-05-20 11:11:11",
  "updateTime": "2022-05-20 11:11:11"
}

###
### 时间参数转Date类型
POST {{host}}/date/add
Content-Type: application/json

{
  "id": 1,
  "name":"yangfei",
  "createTime": "2022-05-20 11:11:11",
  "updateTime": "2022-05-20 11:11:11"
}

### 时间参数转Date类型
POST {{host}}/date/add
Content-Type: application/json

{
  "id": 1,
  "createTime": "2022-05-20 11:11:11"
}

### 时间参数转Date类型
POST {{host}}/date/add
Content-Type: application/json

{
  "id": 1,
  "date": "2022-05-20"
}

### 时间参数转Date类型
POST http://114.251.181.133:30898/test/CodeManageMain/codeDefinition/v1/queryList
Content-Type: application/json
